runtime: python313
service: default
entrypoint: gunicorn --bind :$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker app.main:app

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.9

env_variables:
  USERNAME: "admin"
  PASSWORD_HASH: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # SHA256 of "password"
  FIRESTORE_PROJECT: "your-project-id"
  SECRET_KEY: "your-secret-key-here-generate-a-random-string"
  ENVIRONMENT: "production"
  AES_KEY: "your-aes-key-here-any-string-will-be-hashed-with-sha256"
