runtime: python
service: default
env: flex
entrypoint: gunicorn -b :$PORT --worker-class uvicorn.workers.UvicornWorker app.main:app
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.13"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  USERNAME: "admin"
  PASSWORD_HASH: "5f4dcc3b5aa765d61d8327deb882cf99"  # MD5 of "password"
  FIRESTORE_PROJECT: "your-project-id"
  SECRET_KEY: "your-secret-key-here-generate-a-random-string"
  ENVIRONMENT: "production"
